<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="HIBACL56898" ignored="0" name="TestMotorola" tests="2" failures="1" timestamp="2020-07-07T01:03:45 IST" time="24.912" errors="0">
  <testcase name="sampleFailTestCase" time="0.031" classname="framework.SearchTest">
    <failure type="java.lang.AssertionError" message="expected [4] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [4] but found [2]
at framework.SearchTest.sampleFailTestCase(SearchTest.java:37)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- sampleFailTestCase -->
  <testcase name="samplePassTestCase" time="0.825" classname="framework.SearchTest"/>
</testsuite> <!-- TestMotorola -->
